# Generated by Django 2.1.7 on 2020-02-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200216_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('cover', models.ImageField(blank=True, upload_to='tours/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title',
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='detail',
            name='the_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
    ]
