# Generated by Django 2.1.7 on 2020-02-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200216_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Продолжительность'),
        ),
    ]
