# Generated by Django 2.1.7 on 2020-02-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='subtitle',
            field=models.CharField(max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
    ]
