# Generated by Django 2.1.7 on 2020-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_detail_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='cost',
            field=models.CharField(max_length=200, null=True, verbose_name='Цена'),
        ),
    ]
