# Generated by Django 2.1.7 on 2020-02-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Подзаголовок'),
        ),
    ]
