# Generated by Django 2.1.7 on 2020-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200216_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
    ]
